INSERT INTO DEVICE VALUES('1', 'WINDOWS', 'Windows Workstation');
INSERT INTO DEVICE VALUES('2', 'WINDOWS', 'Windows Server');
INSERT INTO DEVICE VALUES('3', 'MAC', 'Mac Book');
INSERT INTO DEVICE VALUES('4', 'MAC', 'Mac Air');
INSERT INTO DEVICE VALUES('5', 'MAC', 'Mac Pro');
INSERT INTO SERVICE VALUES('1', 4.00, 'Device', 'ANY');
INSERT INTO SERVICE VALUES('2', 5.00, 'Antivirus', 'WINDOWS');
INSERT INTO SERVICE VALUES('3', 7.00, 'Antivirus', 'MAC');
INSERT INTO SERVICE VALUES('4', 3.00, 'Backup', 'ANY');
INSERT INTO SERVICE VALUES('5', 1.00, 'Screen Share', 'ANY');

-- Insert data: Windows Device 1
INSERT INTO SERVICE_ASSIGN VALUES('1', '1', '2'); --Antivirus
INSERT INTO SERVICE_ASSIGN VALUES('2', '1', '4'); --Backup
INSERT INTO SERVICE_ASSIGN VALUES('3', '1', '5'); --SS
-- Insert data: Windows Device 2
INSERT INTO SERVICE_ASSIGN VALUES('4', '2', '2'); --Antivirus
--INSERT INTO SERVICE_ASSIGN VALUES('12', '2', '4'); --Backup
INSERT INTO SERVICE_ASSIGN VALUES('5', '2', '5'); --SS

-- Insert data: Mac Device 1
INSERT INTO SERVICE_ASSIGN VALUES('6', '3', '3'); --Antivirus
INSERT INTO SERVICE_ASSIGN VALUES('7', '3', '4'); --Backup
INSERT INTO SERVICE_ASSIGN VALUES('8', '3', '5'); --SS
-- Insert data: Mac Device 2
INSERT INTO SERVICE_ASSIGN VALUES('9', '4', '3'); --Antivirus
INSERT INTO SERVICE_ASSIGN VALUES('10', '4', '4'); --Backup
INSERT INTO SERVICE_ASSIGN VALUES('11', '4', '5'); --SS
-- Insert data: Mac Device 3
INSERT INTO SERVICE_ASSIGN VALUES('12', '5', '3'); --Antivirus
